/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
created: Tue Jun 28 19:55:51 2022
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { angleToRadians } from '../../../Helpers/angleToRadians';

export default function WaterPill({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/water-pill/water-pill.glb')
  return (
    <group rotation={[0.45,0,0]} position={[0,0,0]} scale={1} ref={group} {...props} dispose={null}>
      <group position={[0,0,0.008]}>
        <mesh geometry={nodes.Sphere.geometry} material={materials['lambert2.003']}    position={[0, 0.03, 0.05]}                                    scale={0.007} />
        <mesh geometry={nodes.Sphere001.geometry} material={materials['lambert2.003']} position={[0.01, 0.02, 0.02]}  rotation={[1.84, 0, 0]}        scale={0.01} />
        <mesh geometry={nodes.Sphere002.geometry} material={materials['lambert2.003']} position={[-0.001, 0.07, 0.03]}                                 scale={0.01} />
        <mesh geometry={nodes.Sphere003.geometry} material={materials['lambert2.003']} position={[-0.01, 0.05, 0.04]}                                scale={0.008} />
        <mesh geometry={nodes.Sphere004.geometry} material={materials['lambert2.003']} position={[-0.02, 0.03, 0.03]} rotation={[0, 1.38, 0]}        scale={0.01} />
        <mesh geometry={nodes.Sphere005.geometry} material={materials['lambert2.003']} position={[0.01, 0.05, 0.03]}  rotation={[0, -1.3, 0]}        scale={0.01} />
        <mesh geometry={nodes.Sphere006.geometry} material={materials['lambert2.003']} position={[-0.01, 0.04, 0.02]} rotation={[0, 0, 1.12]}        scale={0} />
        <mesh geometry={nodes.Sphere007.geometry} material={materials['lambert2.003']} position={[0, 0.04, 0.04]}     rotation={[1.53, 0, 3.1]}      scale={0} />
        <mesh geometry={nodes.Sphere008.geometry} material={materials['lambert2.003']} position={[0.01, 0.04, 0.04]}  rotation={[1.86, 1.1, -1.83]}  scale={0} />
        <mesh geometry={nodes.Sphere009.geometry} material={materials['lambert2.003']} position={[0, 0.04, 0.06]}                                    scale={0} />
        <mesh geometry={nodes.Sphere010.geometry} material={materials['lambert2.003']} position={[-0.02, 0.05, 0.04]}                                scale={0} />
        <mesh geometry={nodes.Sphere011.geometry} material={materials['lambert2.003']} position={[-0.01, 0.03, 0.04]}                                scale={0} />
        <mesh geometry={nodes.Sphere012.geometry} material={materials['lambert2.003']} position={[0.02, 0.02, 0.04]}  rotation={[1.3, -0.64, -0.16]} scale={0} />
        <mesh geometry={nodes.Sphere013.geometry} material={materials['lambert2.003']} position={[0, 0.06, 0.04]}                                    scale={0} />
      </group>
      <group>
        <mesh geometry={nodes.polySurface3_1001.geometry} material={materials['standardSurface3.002']} position={[0, -0.03, 0.04]} scale={0.03} />
        <mesh geometry={nodes.polySurface3_2001.geometry} material={materials.transparent_cap}         position={[0, 0.06, 0.04]}  scale={0.03} />
      </group>
    </group>
  )
}

useGLTF.preload('/water-pill/water-pill.glb')
